### ISSUE TITLE
Category URLs Containing ?___SID=U

### ISSUE THREAD

**Issue by sprankhub** [TheExtensionLab/MegaMenu#44]
The category URLs may contain a `?___SID=U` part. It is a bit weird since it is not really shown, but if you do a `bin2hex($url)`, you see `3f5f5f5f5349443d55` at the end, which is exactly the `?___SID=U` part. In order to get rid of it, I think we should process the session IDs. So in [TheExtensionLab_MegaMenu_Helper_Category_Url#L16](https://github.com/TheExtensionLab/MegaMenu/blob/master/app/code/community/TheExtensionLab/MegaMenu/Helper/Category/Url.php#L16) instead of:

    return Mage::getUrl($category->getMenuLink());

we should do a:

    $url = Mage::getUrl($category->getMenuLink());
    $url = Mage::getModel('core/url')->sessionUrlVar($url);
    return $url;

This may be needed in other places as well, but for me, this did the trick. Could you please check? Thanks!

**Comment by JamesAnelay** [comment]
Should get this released and merged at some point Today simon, or early tomorow if not.

**Comment by JamesAnelay** [comment]
A new version has now been released (1.5.5) and i've also merge the changes into the infinaterenderer branch for you.

Thanks again for your contributions!
