### ISSUE TITLE
HTML tag not closed properly

### ISSUE THREAD

**Issue by adampmoss** [TheExtensionLab/MegaMenu#46]
Online 21 of **/theextensionlab/megamenu/products/featured-secondary.phtml** there appears to be a sudden break in the HTML. Not made a PR because not sure if it's supposed to be either of the following:

`<div class="featured-product">`
or
`<div class="featured-product <?php echo $this->getDisplayClass();?>">`

https://github.com/TheExtensionLab/MegaMenu/blob/master/app/design/frontend/base/default/template/theextensionlab/megamenu/products/featured-secondary.phtml#L21

**Comment by JamesAnelay** [comment]
Ahh nice catch! Looks like the extra '">' is hiding up on line 14 after I moved the DisplayClass.

Will fix now.

**Comment by JamesAnelay** [comment]
Fixed in new release :0 thanks again.
