### ISSUE TITLE
Hide Category on Top Level, But Show on Second Level

### ISSUE THREAD

**Issue by sprankhub** [TheExtensionLab/MegaMenu#48]
Let us assume the following category structure (Catalog > Manage Categories):

```
cat A (include_in_menu = 1)
cat B (include_in_menu = 0)
    cat B1 (include_in_menu = 1)
    cat B2 (include_in_menu = 1)
    cat B3 (include_in_menu = 1)
cat C (include_in_menu = 1)
````

What I would like to achieve is the following output in the megamenu (frontend):

```
cat A
    cat B
    cat B1
    cat B2
    cat B3
cat C
````

So basically, in the megamenu in  the frontend, cat B should NOT be shown as a first-level category, but **only** as a sub item of cat A. I tried this with the `include_in_menu` settings above, but this does not work. I try to output cat B with a `theextensionlab_megamenu/widget_category_list`, but it is not shown.

By the way, in earlier versions (at least in 1.1.0), this worked, because somehow the `include_in_menu` setting has only been respected for top level categories I think.

Do you have any solution for this issue?

**Comment by JamesAnelay** [comment]
Hi Simon,
So the only way I can think to do this would be to add come kind of check in the topmenu/renderer.phtml file.

Maybe that looks like

```
<?php foreach($children as $child):?>
    <?php if($child->getIncludeInMenu() && $child->getIsExcludedFromTopLevel()):?>
```

Not getIsExcludedFromTopLevel doesn't currently exist, but you could either implement it as a function that just checks the IDS or follow http://blog.theextensionlab.com/extensions-customisation/2015/10/06/adding-a-custom-attribute-to-theextensionlab-mega-menu.html and add you own attribute to the category and include it in the load.

**Comment by JamesAnelay** [comment]
I belive the reason this worked in 1.1.0 was before that time I hadn't fixed a performance issue on large catalogs. (I think one your reported). Without this include_in_menu check on subcategories the site would be way to slow on websites with large category structures.

**Comment by sprankhub** [comment]
Hmm okay. Indeed, I do not really see any nice option to do this without custom development. Thanks for the idea and your feedback though!

**Comment by JamesAnelay** [comment]
Note - if you do this as a pull request I would be happy to merge it in.
