### ISSUE TITLE
*PRIO* theextensionlab_megamenu/config_source_dropdown_type for the Attribute "menu_dropdown_type" was not found

### ISSUE THREAD

**Issue by psolutions-me** [TheExtensionLab/MegaMenu#50]
Hi!

There was a installation of your extension. But after activation it has disabled automatically the actual menu style without do anything.

So I have deactivated all installed and dependend modules and now there is this issue displaying when trying to open Catalog > Manage Categories

These modules were installed due the dependencies and are now all OFF
- TheExtensionLab_WidgetImage.xml
- TheExtensionLab_TinyMceConfig.xml
- TheExtensionLab_MegaMenu.xml

Compiler was OFF, All Caches flushed. No results.

Please provide how to fix it shortly...

Regards

**Comment by JamesAnelay** [comment]
Hi,
You will need to go to the `eav_attribute` table. And remove set the source_model to NULL or remove the MegaMenu attributes. You can use this sql to find them. And then manually update them usuing phpmyadmin. 

```
SELECT * FROM `eav_attribute` WHERE `source_model` LIKE '%theextensionlab%'
```

My recommendation would be to always test extensions in a staging environment before installing.

**Comment by psolutions-me** [comment]
Thanks! Let me check!

Yeah... it is like always...

Always test on dev server and than moving to live.
And like always at 4:00am it was faster. Damn!

**Comment by psolutions-me** [comment]
Yeah... now it works, I took a dump of the DB before deleting, so will be able to restore this on live after setting all up on dev.

Thanks for now for fast response!
