### ISSUE TITLE
Dropdown example screencast gone

### ISSUE THREAD

**Issue by rbrown** [TheExtensionLab/MegaMenu#53]
The documentation has a dropdown example page that should link to a video that is hosted on quickcast, but they seem to have gone away https://twitter.com/quickcast/status/911540324761300992

Is there another source for this? Thanks

**Comment by JamesAnelay** [comment]
Afraid not Richard, is there anything specific you need help with in the
drop down?

- james

**Comment by rbrown** [comment]
Hi James, there wasn't, I was just reading through the documentation and was curious, thank you
